### PR TITLE
Accept include_from_page_type config

### PR DESCRIPTION
**Pull request by lilireece**
In my case, I want to apply this module on one page type only. But there are many page types in my code base. I do not want to list them one by one in the exclude_from_page_type setting. So I added the include_from_page_type to make it flexible in different situations.

### CODE REVIEW

**Comment by scott1702** [comment]
@lilireece Care to rebase? :)

**Comment by sheadawson** [comment]
@lilireece Sorry for the late response on this one. This would be a great addition to the module. I wonder if we could change the language slightly though as `include_from_page_types` doesn't sound quite right. Would you mind changing it to `restrict_to_page_types`? Or if anyone has any better suggestions let me know. 

Ideally I think `pagetype_whitelist` and `pagetype_blacklist` would be the most clear and consistent. Maybe we could change to this while keeping backwards compatibility for `exclude_from_page_types`?

**Comment by lilireece** [comment]
@sheadawson No worries. As long as we can use include page types, it would be convenient for those people with lots of page types.

**Comment by sheadawson** [comment]
Thanks guys, I've taken what you've done and implemented config options for `pagetype_blacklist`, `pagetype_whitelist` and legacy support for `exclude_from_page_types`

**Pull request closed without merging**
